/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package data_structures;
import DlinkedList.*;

public class App {
    public static void main(String[] args) {
//        SinglyLinkedList list = new SinglyLinkedList();
//
//        list = list.insert(list, "Slide 1");
//        list = list.insert(list, "Slide 2");
//        list = list.insert(list, "Slide 3");
//        list = list.insert(list, "Slide 4");
//        
//        list.printList(list);
    
    
        DoublyLinkedList list = new DoublyLinkedList();

        list = list.insertAfter(list, "Slide 1");
        list = list.insertAfter(list, "Slide 2");
        list = list.insertAfter(list, "Slide 3");
        list = list.insertAfter(list, "Slide 4");
        
//        String slide_2 = list.getNext(list.getHead()).getData();
//        System.out.println(list.getPrevious(list.getNext(list.getHead())));
//        System.out.println("Size: " + list.getSize());
        System.out.println(list);
    
//        System.out.println(list.getHead().getData());
//        list.printList(list.getHead());
        
    }
}
